from .config_backtester import ROOT_DIR

RESEARCH_DIR = ROOT_DIR / "research"
DATA_DIR = RESEARCH_DIR / "data"
OUTPUTS_DIR = RESEARCH_DIR / "outputs"
TABLES_DIR = OUTPUTS_DIR / "tables"
FIGURES_DIR = OUTPUTS_DIR / "figures"
TABLE_FORMATS = ("csv",)

# Paper dataset — generated by  research/paper_replication/bootstrap/bootstrap_data.py
PAPER_MEMBERSHIP_PATH = DATA_DIR / "membership.parquet"
PAPER_PRICES_ADJUSTED_PATH = DATA_DIR / "prices_adjusted.parquet"
PAPER_PRICES_RAW_PATH = DATA_DIR / "prices_raw.parquet"
PAPER_UNIVERSE_415_TICKERS_PATH = DATA_DIR / "universe_415.csv"
PAPER_PRICES_ADJUSTED_415_PATH = DATA_DIR / "prices_adjusted_415.parquet"
PAPER_PRICES_RAW_415_PATH = DATA_DIR / "prices_raw_415.parquet"
SOURCE_DIR = RESEARCH_DIR / "source"
SOURCE_SIMULATION_DIR = SOURCE_DIR / "Simulation Codes"
PAPER_FACTOR_CANDIDATE_PATHS = (
    DATA_DIR / "factors.parquet",
    DATA_DIR / "factors.csv",
    DATA_DIR / "fm_factors.parquet",
    DATA_DIR / "fm_factors.csv",
    SOURCE_SIMULATION_DIR / "FMdata.parquet",
    SOURCE_SIMULATION_DIR / "FMdata.csv",
    SOURCE_SIMULATION_DIR / "FMdata.mat",
)

TRADING_DAYS_PER_YEAR = 252
DEFAULT_METHODS = ("distance", "cointegration")
REPORT_START_DATE = "2010-03-05"
REPORT_END_DATE = "2018-03-15"
HEADLINE_TC_PER_SHARE = 0.0
PAPER_REFERENCE_UNIVERSE_SIZE = 415
REPORT_METRIC_COLUMNS = (
    "mean_return",
    "sharpe",
    "skewness",
    "kurtosis",
    "max_drawdown",
    "var_95",
    "cvar_95",
    "pct_positive",
    "n_full",
    "n_partial",
    "n_non",
    "n_pairs",
)
PAPER_COMPARISON_TARGETS = {
    "distance": {"std_ret": -0.55, "wav_ret": 11.82, "std_sr": -0.21, "wav_sr": 3.69},
    "cointegration": {"std_ret": -1.81, "wav_ret": 9.66, "std_sr": -0.40, "wav_sr": 2.82},
}
FIGURE_FILE_NAMES = {
    "fig01_pyramid": "figure1_pyramid_algorithm_of_mallat",
    "fig02_example_spread": "figure2_example_pair_spread_and_trades",
    "fig03_example_returns": "figure3_example_pair_return_series",
    "fig04_cumulative_distance": "figure4_cumulative_excess_returns_distance",
    "fig04_cumulative_cointegration": "figure4_cumulative_excess_returns_cointegration",
    "fig05_daily_sharpe_distance": "figure5_daily_sharpe_ratios_distance",
    "fig05_daily_sharpe_cointegration": "figure5_daily_sharpe_ratios_cointegration",
    "fig06_categories_cointegration": "figure6_yearly_proportions_and_returns_cointegration",
    "fig07_categories_distance": "figure7_yearly_proportions_and_returns_minimum_distance",
    "fig08_noise_corr_distance": "figure8_filtered_noise_correlation_distance",
    "fig08_noise_corr_cointegration": "figure8_filtered_noise_correlation_cointegration",
    "fig09_yearly_alpha_distance": "figure9_yearly_abnormal_returns_distance",
    "fig09_yearly_alpha_cointegration": "figure9_yearly_abnormal_returns_cointegration",
    "fig10_wavelet_classes_distance": "figure10_returns_alternative_wavelet_classes_distance",
    "fig10_wavelet_classes_cointegration": "figure10_returns_alternative_wavelet_classes_cointegration",
    "fig11_horizons_distance": "figure11_profits_different_trading_periods_distance",
    "fig11_horizons_cointegration": "figure11_profits_different_trading_periods_cointegration",
    "fig12_convergence_jump_distance": "figure12_convergence_jump_distance",
    "fig12_convergence_jump_cointegration": "figure12_convergence_jump_cointegration",
}

# Fixed parameters for the paper replication workflow.
PAIRS_CONFIG = {
    "wavelet": "sym20",
    "wavelet_boundary": "symmetric",
    "block_size": 252,
    "method": "distance",
    "top_n": 1000,
    "candidate_pool": 2000,
    "k_ar_diff": 1,
    "threshold_sigma": 2.0,
    "tc_per_share": 0.001,
    "index_id": "SPX",
    "max_beta": 10.0,
    "raw_prices": True,
    "paper_periods": [
        ("2010-03-05", "2011-03-03", "2011-03-04", "2012-03-05"),
        ("2011-03-04", "2012-03-05", "2012-03-06", "2013-03-08"),
        ("2012-03-06", "2013-03-08", "2013-03-11", "2014-03-10"),
        ("2013-03-11", "2014-03-10", "2014-03-11", "2015-03-12"),
        ("2014-03-11", "2015-03-12", "2015-03-13", "2016-03-15"),
        ("2015-03-13", "2016-03-15", "2016-03-16", "2017-03-15"),
        ("2016-03-16", "2017-03-15", "2017-03-16", "2018-03-15"),
    ],
    "start_date": "2010-03-01",
    "end_date": "2018-03-31",
    "max_periods": None,
}

DEFAULT_WAVELET = PAIRS_CONFIG["wavelet"]
